/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResenhaRouteImport } from './routes/resenha'
import { Route as RachasRouteImport } from './routes/rachas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtletaUserIdRouteImport } from './routes/atleta.$userId'

const ResenhaRoute = ResenhaRouteImport.update({
  id: '/resenha',
  path: '/resenha',
  getParentRoute: () => rootRouteImport,
} as any)
const RachasRoute = RachasRouteImport.update({
  id: '/rachas',
  path: '/rachas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaUserIdRoute = AtletaUserIdRouteImport.update({
  id: '/atleta/$userId',
  path: '/atleta/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/rachas': typeof RachasRoute
  '/resenha': typeof ResenhaRoute
  '/atleta/$userId': typeof AtletaUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/rachas': typeof RachasRoute
  '/resenha': typeof ResenhaRoute
  '/atleta/$userId': typeof AtletaUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/rachas': typeof RachasRoute
  '/resenha': typeof ResenhaRoute
  '/atleta/$userId': typeof AtletaUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/perfil'
    | '/rachas'
    | '/resenha'
    | '/atleta/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/perfil' | '/rachas' | '/resenha' | '/atleta/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/perfil'
    | '/rachas'
    | '/resenha'
    | '/atleta/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RachasRoute: typeof RachasRoute
  ResenhaRoute: typeof ResenhaRoute
  AtletaUserIdRoute: typeof AtletaUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resenha': {
      id: '/resenha'
      path: '/resenha'
      fullPath: '/resenha'
      preLoaderRoute: typeof ResenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rachas': {
      id: '/rachas'
      path: '/rachas'
      fullPath: '/rachas'
      preLoaderRoute: typeof RachasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/$userId': {
      id: '/atleta/$userId'
      path: '/atleta/$userId'
      fullPath: '/atleta/$userId'
      preLoaderRoute: typeof AtletaUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RachasRoute: RachasRoute,
  ResenhaRoute: ResenhaRoute,
  AtletaUserIdRoute: AtletaUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
