/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResenhaRouteImport } from './routes/resenha'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RachasRouteImport } from './routes/rachas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatConversaIdRouteImport } from './routes/chat.$conversaId'
import { Route as AtletaUserIdRouteImport } from './routes/atleta.$userId'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api.public.mp-webhook'

const ResenhaRoute = ResenhaRouteImport.update({
  id: '/resenha',
  path: '/resenha',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RachasRoute = RachasRouteImport.update({
  id: '/rachas',
  path: '/rachas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversaIdRoute = ChatConversaIdRouteImport.update({
  id: '/chat/$conversaId',
  path: '/chat/$conversaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletaUserIdRoute = AtletaUserIdRouteImport.update({
  id: '/atleta/$userId',
  path: '/atleta/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/rachas': typeof RachasRoute
  '/ranking': typeof RankingRoute
  '/resenha': typeof ResenhaRoute
  '/atleta/$userId': typeof AtletaUserIdRoute
  '/chat/$conversaId': typeof ChatConversaIdRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/rachas': typeof RachasRoute
  '/ranking': typeof RankingRoute
  '/resenha': typeof ResenhaRoute
  '/atleta/$userId': typeof AtletaUserIdRoute
  '/chat/$conversaId': typeof ChatConversaIdRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/rachas': typeof RachasRoute
  '/ranking': typeof RankingRoute
  '/resenha': typeof ResenhaRoute
  '/atleta/$userId': typeof AtletaUserIdRoute
  '/chat/$conversaId': typeof ChatConversaIdRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/login'
    | '/perfil'
    | '/rachas'
    | '/ranking'
    | '/resenha'
    | '/atleta/$userId'
    | '/chat/$conversaId'
    | '/api/public/mp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/login'
    | '/perfil'
    | '/rachas'
    | '/ranking'
    | '/resenha'
    | '/atleta/$userId'
    | '/chat/$conversaId'
    | '/api/public/mp-webhook'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/login'
    | '/perfil'
    | '/rachas'
    | '/ranking'
    | '/resenha'
    | '/atleta/$userId'
    | '/chat/$conversaId'
    | '/api/public/mp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RachasRoute: typeof RachasRoute
  RankingRoute: typeof RankingRoute
  ResenhaRoute: typeof ResenhaRoute
  AtletaUserIdRoute: typeof AtletaUserIdRoute
  ChatConversaIdRoute: typeof ChatConversaIdRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resenha': {
      id: '/resenha'
      path: '/resenha'
      fullPath: '/resenha'
      preLoaderRoute: typeof ResenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rachas': {
      id: '/rachas'
      path: '/rachas'
      fullPath: '/rachas'
      preLoaderRoute: typeof RachasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversaId': {
      id: '/chat/$conversaId'
      path: '/chat/$conversaId'
      fullPath: '/chat/$conversaId'
      preLoaderRoute: typeof ChatConversaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleta/$userId': {
      id: '/atleta/$userId'
      path: '/atleta/$userId'
      fullPath: '/atleta/$userId'
      preLoaderRoute: typeof AtletaUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RachasRoute: RachasRoute,
  RankingRoute: RankingRoute,
  ResenhaRoute: ResenhaRoute,
  AtletaUserIdRoute: AtletaUserIdRoute,
  ChatConversaIdRoute: ChatConversaIdRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
